# Generated by Django 2.2.6 on 2020-01-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work_exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('P_1', models.CharField(max_length=500)),
                ('P_2', models.CharField(max_length=500)),
                ('P_3', models.CharField(max_length=500)),
            ],
        ),
    ]
