# Generated by Django 2.2.6 on 2020-01-17 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0002_work_exp_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='inputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_f', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='work_exp',
            name='location',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_app.inputs')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='Add the tag for this project')),
                ('img_num', models.CharField(blank=True, max_length=50)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_app.Skills')),
            ],
        ),
    ]
