# Generated by Django 2.2.6 on 2020-01-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0003_auto_20200117_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inputs',
            new_name='input',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
