# Generated by Django 2.2.6 on 2020-01-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0005_auto_20200118_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skill',
        ),
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(to='p_app.Skill'),
        ),
    ]
