# Generated by Django 2.2.6 on 2020-01-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0006_auto_20200118_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='input',
        ),
    ]
