# Generated by Django 2.2.6 on 2020-01-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0009_auto_20200118_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
