# Generated by Django 2.2.6 on 2020-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0014_auto_20200118_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
