# Generated by Django 2.2.6 on 2020-01-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0015_description_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
