# Generated by Django 2.2.6 on 2020-01-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0017_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
