# Generated by Django 2.2.6 on 2020-01-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0018_auto_20200118_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('Name', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=75, null=True)),
                ('linkedin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
            ],
        ),
    ]
