# Generated by Django 2.2.6 on 2020-03-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0019_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_Frameworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=50)),
                ('frameworks', models.ManyToManyField(to='p_app.Skill')),
            ],
        ),
    ]
