# Generated by Django 2.2.6 on 2020-03-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0020_tech_frameworks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tech_Frameworks',
            new_name='Tech_Framework',
        ),
    ]
