# Generated by Django 2.2.6 on 2020-03-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0021_auto_20200306_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_exp',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
