# Generated by Django 2.2.6 on 2020-03-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0022_work_exp_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_pb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value_percent', models.IntegerField()),
            ],
        ),
    ]
