# Generated by Django 2.2.6 on 2020-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0023_skill_pb'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_pb',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
