# Generated by Django 2.2.6 on 2020-03-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0024_skill_pb_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_pb',
            name='icon_tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
